#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Mar 23 12:56:13 IST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=6
shaderPack=ComplementaryReimagined_r5.7.1.zip
