#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Apr 03 17:08:30 IST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=6
shaderPack=Sildur's Enhanced Default v1.19 Fancy.zip
